export const EXPENSE_NAME_SUGGESTIONS = [
    'Dîner entre potes',
    'Courses du mois',
    'Resto du midi',
    'Soirée ciné',
    'Apéro du vendredi',
    'Pizza à emporter',
    'Courses de la soirée',
    'Brunch du dimanche',
    'Kebab nocturne',
    'Petit-déj en ville',
    'Goûter au café',
    'BBQ chez Marc',
    'Sortie bowling',
    "Courses pour l'appart",
    'Picnic au parc',
];

export const GROUP_NAME_SUGGESTIONS = [
    'Soirée entre amis',
    'Dîner entre potes',
    "Fête d'anniversaire",
    'Cinéma et pop-corn',
    'Apéro convivial',
    'Soirée pizza',
    'Brunch entre amis',
    'Kebab festif',
    'Petit-déj ensemble',
    'Goûter gourmand',
    'BBQ en plein air',
    'Bowling fun',
    'Picnic au parc',
    'Soirée jeux',
    'Chill entre amis',
];
