export const getRandomEmoji = (): string => {
    const emojis: string[] = [
        '🌲',
        '🌳',
        '🌴',
        '🌵',
        '🌾',
        '🌿',
        '🍀',
        '🍁',
        '🍂',
        '🍃',
        '🌸',
        '🌼',
        '🌻',
        '🌺',
        '🌹',
        '🌷',
        '⚽',
        '🏀',
        '🏈',
        '⚾',
        '🎾',
        '🏐',
        '🏉',
        '🎱',
        '🏓',
        '🏸',
        '🥅',
        '🏒',
        '🏑',
        '🏏',
        '🥍',
        '🏹',
        '🎣',
        '🥊',
        '🥋',
        '🎽',
        '🛹',
        '⛸',
        '🛷',
        '🏂',
    ];

    const randomIndex = Math.floor(Math.random() * emojis.length);
    return emojis[randomIndex];
};
