export const EMOJIS: { [key: string]: string[] } = {
    '😀': [
        'sourire',
        'visage',
        'visage avec grand sourire',
        'bouche',
        'ouvert',
    ],
    '😃': [
        'sourire',
        'visage',
        'visage avec grand sourire et de grands yeux',
        'bouche',
        'grand',
        'œil',
        'ouvert',
    ],
    '😄': [
        'sourire',
        'visage',
        'visage souriant avec des yeux rieurs',
        'œil',
        'bouche',
        'rire',
    ],
    '😁': [
        'sourire',
        'visage',
        'visage rayonnant aux yeux rieurs',
        'œil',
        'content',
    ],
    '😆': [
        'sourire',
        'visage',
        'visage souriant aux yeux plissés',
        'bouche',
        'content',
        'rire',
        'ouvert',
    ],
    '😅': [
        'sourire',
        'visage',
        'visage souriant avec une goutte de sueur',
        'froid',
        'goutte',
        'sueur',
    ],
    '🤣': ['mdr', 'mort de rire', 'visage', 'pleurer', 'rire'],
    '😂': ['rire', 'visage', 'visage qui pleure de joie', 'joyeux', 'pleurer'],
    '🙂': ['sourire', 'visage', 'visage souriant légèrement'],
    '🙃': ['visage', 'visage à l’envers', 'à l’envers'],
    '😉': ['clin d’œil', 'visage', 'visage faisant un clin d’œil'],
    '😊': [
        'heureux',
        'sourire',
        'visage',
        'visage souriant avec les yeux plissés',
        'plaisir',
        'rougeaud',
    ],
    '😇': [
        'ange',
        'auréole',
        'visage',
        'visage souriant avec auréole',
        'fantastique',
        'conte',
    ],
    '🥰': [
        'amoureux',
        'visage souriant avec 3 cœurs',
        'cœur',
        'visage',
        'admiration',
    ],
    '😍': [
        'cœur',
        'visage',
        'visage souriant avec des yeux en cœur',
        'amour',
        'œil',
    ],
    '🤩': [
        'étoile',
        'visage',
        'visage avec des étoiles à la place des yeux',
        'œil',
        'admiration',
    ],
    '😘': ['baiser', 'cœur', 'visage', 'visage envoyant un baiser', 'bisou'],
    '😗': ['baiser', 'visage', 'visage faisant un bisou', 'bisou'],
    '😚': [
        'baiser',
        'visage',
        'visage faisant un bisou, yeux fermés',
        'bisou',
        'œil',
        'fermé',
    ],
    '😙': [
        'baiser',
        'sourire',
        'visage',
        'visage souriant faisant un bisou',
        'bisou',
        'œil',
    ],
    '😋': [
        'délicieux',
        'sourire',
        'visage',
        'visage qui savoure un bon plat',
        'miam',
    ],
    '😛': ['langue', 'visage', 'visage qui tire la langue'],
    '😜': [
        'clin d’œil',
        'langue',
        'visage',
        'visage qui tire la langue en faisant un clin d’œil',
        'œil',
    ],
    '🤪': ['grimace', 'visage', 'visage qui grimace', 'grand', 'œil', 'petit'],
    '😝': [
        'langue',
        'visage',
        'visage qui tire la langue, les yeux plissés',
        'œil',
        'plissé',
    ],
    '🤑': [
        'argent',
        'bouche',
        'visage',
        'visage avec une bouche pleine de billets',
        'riche',
    ],
    '🤗': ['câlin', 'visage', 'visage faisant un câlin', 'ouvert', 'bras'],
    '🤭': ['ho', 'main sur la bouche', 'visage', 'oups', 'surprise'],
    '🤫': ['chut', 'doigt sur la bouche', 'visage', 'silence'],
    '🤔': ['réfléchir', 'visage', 'visage en pleine réflexion', 'pensée'],
    '🤐': [
        'bouche',
        'fermeture éclair',
        'visage',
        'visage avec une fermeture éclair sur la bouche',
        'motus',
    ],
    '🤨': ['sourcil levé', 'visage', 'méfiant', 'sceptique'],
    '😐': ['neutre', 'visage', 'visage neutre', 'bouche', 'fermé'],
    '😑': ['inexpressif', 'visage', 'visage inexpressif'],
    '😶': ['muet', 'visage', 'visage sans bouche', 'bouche'],
    '😏': [
        'sourire en coin',
        'visage',
        'visage avec un sourire en coin',
        'narquois',
    ],
    '😒': ['ennuyé', 'visage', 'visage blasé', 'mécontent'],
    '🙄': ['yeux au ciel', 'visage', 'visage roulant des yeux', 'agacement'],
    '😬': ['grimace', 'visage', 'visage grimaçant', 'dents'],
    '🤥': ['mentir', 'nez', 'visage', 'visage de menteur', 'pinocchio'],
    '😌': ['soulagé', 'visage', 'visage soulagé'],
    '😔': ['pensif', 'visage', 'visage pensif', 'triste'],
    '😪': ['endormi', 'visage', 'visage endormi', 'sommeil'],
    '🤤': ['bave', 'visage', 'visage qui bave', 'faim'],
    '😴': ['dormir', 'visage', 'visage endormi', 'sommeil', 'zzz'],
    '😷': [
        'docteur',
        'malade',
        'masque',
        'visage',
        'visage avec un masque chirurgical',
        'froid',
    ],
    '🤒': [
        'fièvre',
        'malade',
        'thermomètre',
        'visage',
        'visage avec un thermomètre',
    ],
    '🤕': [
        'blessé',
        'pansement',
        'visage',
        'visage avec un pansement à la tête',
    ],
    '🤢': ['nausée', 'visage', 'visage nauséeux', 'malade', 'vomir'],
    '🤮': ['vomir', 'visage', 'visage qui vomit', 'malade'],
    '🤧': ['éternuement', 'mouchoir', 'visage', 'visage qui éternue', 'malade'],
    '🥵': ['chaud', 'rouge', 'sueur', 'visage', 'visage rouge et chaud'],
    '🥶': ['froid', 'bleu', 'glaçon', 'visage', 'visage bleu de froid'],
    '🥴': ['confus', 'étourdi', 'visage', 'visage avec une expression confuse'],
    '😵': ['étourdi', 'visage', 'visage étourdi', 'vertige'],
    '🤯': ['exploser', 'tête', 'visage', 'tête qui explose', 'choqué'],
    '🤠': ['chapeau', 'cow-boy', 'visage', 'visage avec un chapeau de cow-boy'],
    '🥳': ['fête', 'chapeau', 'visage', 'visage festif', 'cotillons'],
    '😎': [
        'lunettes de soleil',
        'sourire',
        'visage',
        'visage souriant avec des lunettes de soleil',
        'cool',
    ],
    '🤓': ['intello', 'lunettes', 'visage', 'visage d’intello'],
    '🧐': ['monocle', 'visage', 'visage avec un monocle', 'curieux'],
    '😕': ['confus', 'visage', 'visage confus'],
    '😟': ['inquiet', 'visage', 'visage inquiet'],
    '🙁': ['légèrement triste', 'visage', 'visage légèrement mécontent'],
    '😮': ['bouche bée', 'visage', 'visage avec la bouche bée', 'surprise'],
    '😯': ['bouche cousue', 'visage', 'visage sans voix', 'surprise'],
    '😲': ['stupéfait', 'visage', 'visage stupéfait', 'choc'],
    '😳': ['rouge', 'visage', 'visage rouge de honte', 'gêné'],
    '🥺': ['implorer', 'visage', 'visage qui implore', 'yeux', 'larmoyant'],
    '😦': [
        'froncer les sourcils',
        'visage',
        'visage mécontent avec la bouche ouverte',
        'triste',
    ],
    '😧': ['angoissé', 'visage', 'visage angoissé', 'peur'],
    '😨': ['effrayé', 'visage', 'visage effrayé', 'peur'],
    '😰': [
        'sueur froide',
        'visage',
        'visage anxieux avec une goutte de sueur',
        'peur',
    ],
    '😥': [
        'déçu mais soulagé',
        'visage',
        'visage triste mais soulagé',
        'pleurer',
    ],
    '😢': ['pleurer', 'visage', 'visage qui pleure', 'triste', 'larme'],
    '😭': ['sangloter', 'visage', 'visage en larmes', 'pleurer', 'triste'],
    '😱': ['crier', 'visage', 'visage qui crie d’effroi', 'peur', 'munch'],
    '😖': ['confus', 'visage', 'visage déconcerté', 'frustration'],
    '😣': ['persévérer', 'visage', 'visage qui persévère', 'difficulté'],
    '😞': ['déçu', 'visage', 'visage déçu', 'triste'],
    '😓': [
        'sueur',
        'visage',
        'visage abattu avec une goutte de sueur',
        'triste',
    ],
    '😩': ['épuisé', 'visage', 'visage épuisé', 'fatigué'],
    '😫': ['fatigué', 'visage', 'visage las', 'épuisé'],
    '🥱': ['bâiller', 'visage', 'visage qui bâille', 'fatigué'],
    '😤': [
        'triomphe',
        'visage',
        'visage avec de la fumée sortant des naseaux',
        'colère',
    ],
    '😡': ['enragé', 'visage', 'visage enragé', 'colère', 'rouge'],
    '😠': ['colère', 'visage', 'visage en colère'],
    '🤬': [
        'jurer',
        'visage',
        'visage avec des symboles sur la bouche',
        'colère',
    ],
    '😈': [
        'diable',
        'sourire',
        'visage',
        'visage souriant avec des cornes',
        'démon',
        'fantastique',
    ],
    '👿': [
        'diable',
        'colère',
        'visage',
        'visage de diable en colère',
        'démon',
        'fantastique',
    ],
    '💀': ['crâne', 'mort', 'visage'],
    '💩': ['caca', 'crotte', 'tas de crotte'],
    '🤡': ['clown', 'visage', 'visage de clown'],
    '👹': ['ogre', 'monstre', 'visage', 'démon', 'fantastique', 'japonais'],
    '👺': ['gobelin', 'monstre', 'visage', 'démon', 'fantastique', 'japonais'],
    '👻': ['fantôme', 'visage', 'monstre', 'fantastique'],
    '👽': ['extraterrestre', 'visage', 'ovni'],
    '👾': ['alien', 'monstre', 'visage', 'jeu vidéo'],
    '🤖': ['robot', 'visage'],
    '😺': ['sourire', 'chat', 'visage', 'visage de chat souriant', 'animal'],
    '😸': [
        'sourire',
        'chat',
        'visage',
        'visage de chat souriant aux yeux rieurs',
        'animal',
    ],
    '😹': [
        'rire',
        'chat',
        'visage',
        'visage de chat qui pleure de joie',
        'animal',
        'pleurer',
    ],
    '😻': [
        'cœur',
        'chat',
        'visage',
        'visage de chat souriant avec des yeux en cœur',
        'animal',
        'amour',
    ],
    '😼': [
        'sourire en coin',
        'chat',
        'visage',
        'visage de chat avec un sourire en coin',
        'animal',
        'narquois',
    ],
    '😽': [
        'baiser',
        'chat',
        'visage',
        'visage de chat envoyant un baiser',
        'animal',
    ],
    '🙀': [
        'crier',
        'chat',
        'visage',
        'visage de chat fatigué',
        'animal',
        'surprise',
    ],
    '😿': [
        'pleurer',
        'chat',
        'visage',
        'visage de chat qui pleure',
        'animal',
        'triste',
    ],
    '😾': [
        'bouder',
        'chat',
        'visage',
        'visage de chat qui boude',
        'animal',
        'colère',
    ],
    '🙈': ['singe', 'voir', 'ne rien voir', 'interdit'],
    '🙉': ['singe', 'entendre', 'ne rien entendre', 'interdit'],
    '🙊': ['singe', 'parler', 'ne rien dire', 'interdit'],
    '👋': ['salut', 'main', 'signe de la main', 'au revoir'],
    '🤚': ['dos de la main levée', 'main', 'levée'],
    '🖐️': ['main levée doigts écartés', 'main', 'levée'],
    '✋': ['main levée', 'main', 'stop'],
    '🖖': ['salut vulcain', 'main', 'doigts', 'spock'],
    '👌': ['ok', 'main', 'd’accord'],
    '🤌': ['doigts pincés', 'main', 'interrogation', 'italien'],
    '🤏': ['pincement', 'main', 'petit'],
    '✌️': ['victoire', 'main', 'V'],
    '🤞': ['doigts croisés', 'main', 'chance', 'promesse'],
    '🤟': ['je t’aime', 'main', 'amour'],
    '🤘': ['cornes', 'main', 'rock'],
    '🤙': ['appelle-moi', 'main', 'téléphone'],
    '👈': ['doigt pointant à gauche', 'main', 'gauche'],
    '👉': ['doigt pointant à droite', 'main', 'droite'],
    '👆': ['doigt pointant vers le haut', 'main', 'haut'],
    '🖕': ['doigt d’honneur', 'main', 'insulte'],
    '👇': ['doigt pointant vers le bas', 'main', 'bas'],
    '☝️': ['index pointant vers le haut', 'main', 'un'],
    '👍': ['pouce levé', 'main', 'j’aime', 'ok'],
    '👎': ['pouce baissé', 'main', 'je n’aime pas', 'non'],
    '✊': ['poing levé', 'main', 'résistance'],
    '👊': ['poing fermé', 'main', 'coup de poing'],
    '🤛': ['poing vers la gauche', 'main', 'gauche'],
    '🤜': ['poing vers la droite', 'main', 'droite'],
    '👏': ['applaudir', 'mains', 'bravo'],
    '🙌': ['mains levées', 'mains', 'célébration', 'joie'],
    '👐': ['mains ouvertes', 'mains', 'câlin'],
    '🤲': ['mains en coupe', 'mains', 'prière', 'recevoir'],
    '🤝': ['poignée de main', 'mains', 'accord', 'salutation'],
    '🙏': ['mains en prière', 'mains', 'prière', 'merci'],
    '✍️': ['écrire', 'main', 'stylo'],
    '💅': ['vernis à ongles', 'main', 'manucure', 'beauté'],
    '🤳': ['selfie', 'main', 'téléphone'],
    '💪': ['muscle', 'bras', 'force', 'biceps'],
    '🦾': ['bras mécanique', 'prothèse', 'robot'],
    '🦿': ['jambe mécanique', 'prothèse', 'robot'],
    '🦵': ['jambe', 'corps', 'coup de pied'],
    '🦶': ['pied', 'corps', 'coup de pied'],
    '👂': ['oreille', 'corps', 'entendre'],
    '🦻': ['oreille avec appareil auditif', 'corps', 'sourd', 'handicap'],
    '👃': ['nez', 'corps', 'sentir'],
    '🧠': ['cerveau', 'corps', 'intelligence', 'penser'],
    '🦷': ['dent', 'corps', 'dentiste'],
    '🦴': ['os', 'corps', 'squelette'],
    '👀': ['yeux', 'corps', 'regarder', 'voir'],
    '👁️': ['œil', 'corps', 'regarder', 'voir'],
    '👅': ['langue', 'corps', 'goût'],
    '👄': ['bouche', 'corps', 'lèvres', 'baiser'],
    '👶': ['bébé', 'personne', 'enfant'],
    '🧒': ['enfant', 'personne', 'jeune'],
    '👦': ['garçon', 'personne', 'enfant'],
    '👧': ['fille', 'personne', 'enfant'],
    '🧑': ['personne', 'adulte'],
    '👱': ['personne blonde', 'cheveux', 'blond'],
    '👨': ['homme', 'personne', 'adulte'],
    '🧔': ['homme barbu', 'personne', 'barbe'],
    '👨‍🦰': ['homme aux cheveux roux', 'personne', 'roux'],
    '👨‍🦱': ['homme aux cheveux bouclés', 'personne', 'bouclés'],
    '👨‍🦳': ['homme aux cheveux blancs', 'personne', 'vieux'],
    '👨‍🦲': ['homme chauve', 'personne', 'chauve'],
    '👩': ['femme', 'personne', 'adulte'],
    '👩‍🦰': ['femme aux cheveux roux', 'personne', 'roux'],
    '👩‍🦱': ['femme aux cheveux bouclés', 'personne', 'bouclés'],
    '👩‍🦳': ['femme aux cheveux blancs', 'personne', 'vieux'],
    '👩‍🦲': ['femme chauve', 'personne', 'chauve'],
    '🧓': ['personne âgée', 'vieux', 'adulte'],
    '👴': ['vieil homme', 'vieux', 'homme'],
    '👵': ['vieille femme', 'vieux', 'femme'],
    '🙍': ['personne qui fronce les sourcils', 'triste', 'mécontent'],
    '🙎': ['personne qui boude', 'mécontent', 'colère'],
    '🙅': ['personne faisant un geste d’interdiction', 'non', 'interdit'],
    '🙆': ['personne faisant un geste d’approbation', 'oui', 'd’accord'],
    '💁': ['personne au point d’information', 'aide', 'information'],
    '🙋': ['personne levant la main', 'question', 'présent'],
    '🧏': ['personne sourde', 'sourd', 'handicap', 'entendre'],
    '🙇': ['personne qui s’incline', 'respect', 'merci', 'pardon'],
    '🤦': [
        'facepalm',
        'personne se frappant le front',
        'exaspération',
        'erreur',
    ],
    '🤷': [
        'haussement d’épaules',
        'personne haussant les épaules',
        'je ne sais pas',
        'doute',
    ],
    '👨‍⚕️': [
        'professionnel de la santé homme',
        'docteur',
        'infirmier',
        'médecin',
    ],
    '👩‍⚕️': [
        'professionnelle de la santé femme',
        'docteur',
        'infirmière',
        'médecin',
    ],
    '👨‍🎓': ['étudiant', 'diplômé', 'homme'],
    '👩‍🎓': ['étudiante', 'diplômée', 'femme'],
    '👨‍🏫': ['enseignant', 'professeur', 'homme'],
    '👩‍🏫': ['enseignante', 'professeure', 'femme'],
    '👨‍⚖️': ['juge homme', 'justice', 'tribunal'],
    '👩‍⚖️': ['juge femme', 'justice', 'tribunal'],
    '👨‍🌾': ['agriculteur', 'fermier', 'homme'],
    '👩‍🌾': ['agricultrice', 'fermière', 'femme'],
    '👨‍🍳': ['cuisinier', 'chef', 'homme'],
    '👩‍🍳': ['cuisinière', 'cheffe', 'femme'],
    '👨‍🔧': ['mécanicien', 'homme', 'réparation'],
    '👩‍🔧': ['mécanicienne', 'femme', 'réparation'],
    '👨‍🏭': ['ouvrier d’usine', 'homme', 'usine'],
    '👩‍🏭': ['ouvrière d’usine', 'femme', 'usine'],
    '👨‍💼': ['employé de bureau homme', 'bureau', 'travail'],
    '👩‍💼': ['employée de bureau femme', 'bureau', 'travail'],
    '👨‍🔬': ['scientifique homme', 'science', 'laboratoire'],
    '👩‍🔬': ['scientifique femme', 'science', 'laboratoire'],
    '👨‍💻': ['informaticien', 'développeur', 'homme'],
    '👩‍💻': ['informaticienne', 'développeuse', 'femme'],
    '👨‍🎤': ['chanteur', 'artiste', 'homme'],
    '👩‍🎤': ['chanteuse', 'artiste', 'femme'],
    '👨‍🎨': ['artiste peintre homme', 'art', 'peinture'],
    '👩‍🎨': ['artiste peintre femme', 'art', 'peinture'],
    '👨‍✈️': ['pilote homme', 'avion', 'aviation'],
    '👩‍✈️': ['pilote femme', 'avion', 'aviation'],
    '👨‍🚀': ['astronaute homme', 'espace', 'fusée'],
    '👩‍🚀': ['astronaute femme', 'espace', 'fusée'],
    '👨‍🚒': ['pompier homme', 'feu', 'camion'],
    '👩‍🚒': ['pompière femme', 'feu', 'camion'],
    '👮': ['policier', 'police', 'agent'],
    '🕵️': ['détective', 'enquête', 'espion'],
    '💂': ['garde', 'soldat', 'britannique'],
    '👷': ['ouvrier du bâtiment', 'construction', 'casque'],
    '🤴': ['prince', 'royal', 'couronne'],
    '👸': ['princesse', 'royal', 'couronne'],
    '👳': ['personne avec un turban', 'turban', 'Inde'],
    '👲': ['homme avec un calot chinois', 'calot', 'Chine'],
    '🧕': ['femme avec un foulard', 'foulard', 'hijab'],
    '🤵': ['homme en smoking', 'mariage', 'soirée'],
    '👰': ['mariée avec un voile', 'mariage', 'robe'],
    '🤰': ['femme enceinte', 'enceinte', 'bébé'],
    '🤱': ['allaitement', 'bébé', 'mère'],
    '💃': ['danseuse', 'danse', 'femme', 'robe'],
    '🕺': ['danseur', 'danse', 'homme', 'soirée'],
    '👯': ['personnes avec des oreilles de lapin', 'danse', 'fête'],
    '🚶': ['personne qui marche', 'marche', 'piéton'],
    '🏃': ['personne qui court', 'course', 'sport'],
    '🧗': ['personne qui fait de l’escalade', 'escalade', 'montagne'],
    '🤺': ['escrimeur', 'escrime', 'sport'],
    '🏇': ['course de chevaux', 'cheval', 'jockey'],
    '🏂': ['snowboarder', 'snowboard', 'neige', 'sport'],
    '🏌️': ['golfeur', 'golf', 'sport'],
    '🏄': ['surfeur', 'surf', 'vague', 'sport'],
    '🚣': ['personne qui rame', 'aviron', 'bateau', 'sport'],
    '🏊': ['nageur', 'natation', 'piscine', 'sport'],
    '⛹️': ['basketteur', 'basket-ball', 'sport'],
    '🏋️': ['haltérophile', 'haltérophilie', 'poids', 'sport'],
    '🚴': ['cycliste', 'vélo', 'bicyclette', 'sport'],
    '🚵': ['VTT', 'vététiste', 'vélo', 'montagne'],
    '🤸': ['personne qui fait la roue', 'gymnastique', 'sport'],
    '🤼': ['lutteurs', 'lutte', 'sport'],
    '🤽': ['joueur de water-polo', 'water-polo', 'sport'],
    '🤾': ['handballeur', 'handball', 'sport'],
    '🤹': ['jongleur', 'jonglage', 'cirque'],
    '🧘': ['personne en position du lotus', 'yoga', 'méditation'],
    '🛀': ['personne prenant un bain', 'bain', 'baignoire'],
    '🛌': ['personne au lit', 'dormir', 'lit'],
    '👭': ['deux femmes se tenant la main', 'couple', 'amour', 'lesbienne'],
    '👫': ['homme et femme se tenant la main', 'couple', 'amour', 'hétéro'],
    '👬': ['deux hommes se tenant la main', 'couple', 'amour', 'gay'],
    '💏': ['baiser', 'couple', 'amour'],
    '💑': ['couple avec cœur', 'amour', 'romance'],
    '👪': ['famille', 'parents', 'enfants'],
    '🗣️': ['tête qui parle', 'parler', 'silhouette'],
    '👤': ['silhouette de buste', 'personne', 'utilisateur'],
    '👥': ['silhouettes de bustes', 'personnes', 'groupe'],
    '👣': ['empreintes de pas', 'pas', 'marcher'],
    '🐶': ['chien', 'animal', 'tête'],
    '🐱': ['chat', 'animal', 'tête'],
    '🐭': ['souris', 'animal', 'tête'],
    '🐹': ['hamster', 'animal', 'tête'],
    '🐰': ['lapin', 'animal', 'tête'],
    '🦊': ['renard', 'animal', 'tête'],
    '🐻': ['ours', 'animal', 'tête'],
    '🐼': ['panda', 'animal', 'tête'],
    '🐨': ['koala', 'animal', 'tête'],
    '🐯': ['tigre', 'animal', 'tête'],
    '🦁': ['lion', 'animal', 'tête'],
    '🐮': ['vache', 'animal', 'tête'],
    '🐷': ['cochon', 'animal', 'tête'],
    '🐽': ['groin', 'cochon', 'animal', 'nez'],
    '🐸': ['grenouille', 'animal', 'tête'],
    '🐵': ['singe', 'animal', 'tête'],
    '🐔': ['poulet', 'animal', 'oiseau'],
    '🐧': ['pingouin', 'animal', 'oiseau'],
    '🐦': ['oiseau', 'animal'],
    '🐤': ['poussin', 'animal', 'oiseau'],
    '🐣': ['poussin sortant de l’œuf', 'animal', 'oiseau', 'naissance'],
    '🐥': ['poussin de face', 'animal', 'oiseau'],
    '🦆': ['canard', 'animal', 'oiseau'],
    '🦅': ['aigle', 'animal', 'oiseau'],
    '🦉': ['hibou', 'animal', 'oiseau'],
    '🦇': ['chauve-souris', 'animal', 'nuit'],
    '🐺': ['loup', 'animal', 'tête'],
    '🐗': ['sanglier', 'animal', 'cochon'],
    '🐴': ['cheval', 'animal', 'tête'],
    '🦄': ['licorne', 'animal', 'fantastique', 'tête'],
    '🐝': ['abeille', 'animal', 'insecte'],
    '🐛': ['chenille', 'animal', 'insecte'],
    '🦋': ['papillon', 'animal', 'insecte'],
    '🐌': ['escargot', 'animal'],
    '🐞': ['coccinelle', 'animal', 'insecte'],
    '🐜': ['fourmi', 'animal', 'insecte'],
    '🦗': ['grillon', 'animal', 'insecte'],
    '🕷️': ['araignée', 'animal', 'insecte'],
    '🦂': ['scorpion', 'animal'],
    '🦀': ['crabe', 'animal', 'fruit de mer'],
    '🐍': ['serpent', 'animal', 'reptile'],
    '🦎': ['lézard', 'animal', 'reptile'],
    '🐢': ['tortue', 'animal', 'reptile'],
    '🐠': ['poisson tropical', 'animal', 'poisson'],
    '🐟': ['poisson', 'animal'],
    '🐡': ['poisson-globe', 'animal', 'poisson'],
    '🐬': ['dauphin', 'animal', 'mammifère marin'],
    '🐳': ['baleine', 'animal', 'mammifère marin'],
    '🐋': ['baleine à bosse', 'animal', 'mammifère marin'],
    '🐊': ['crocodile', 'animal', 'reptile'],
    '🐆': ['léopard', 'animal', 'félin'],
    '🦓': ['zèbre', 'animal', 'mammifère'],
    '🦍': ['gorille', 'animal', 'singe'],
    '🐘': ['éléphant', 'animal', 'mammifère'],
    '🦏': ['rhinocéros', 'animal', 'mammifère'],
    '🐪': ['chameau', 'animal', 'mammifère'],
    '🐫': ['dromadaire', 'animal', 'mammifère'],
    '🦒': ['girafe', 'animal', 'mammifère'],
    '🐃': ['buffle', 'animal', 'mammifère'],
    '🐂': ['bœuf', 'animal', 'mammifère'],
    '🐄': ['vache', 'animal', 'mammifère'],
    '🐎': ['cheval', 'animal', 'mammifère'],
    '🐖': ['cochon', 'animal', 'mammifère'],
    '🐏': ['bélier', 'animal', 'mammifère'],
    '🐑': ['mouton', 'animal', 'mammifère'],
    '🐐': ['chèvre', 'animal', 'mammifère'],
    '🦌': ['cerf', 'animal', 'mammifère'],
    '🐕': ['chien', 'animal', 'mammifère'],
    '🐩': ['caniche', 'animal', 'chien'],
    '🐈': ['chat', 'animal', 'félin'],
    '🐓': ['coq', 'animal', 'oiseau'],
    '🦃': ['dinde', 'animal', 'oiseau'],
    '🕊️': ['colombe', 'animal', 'oiseau', 'paix'],
    '🐇': ['lapin', 'animal', 'mammifère'],
    '🐁': ['souris', 'animal', 'mammifère'],
    '🐀': ['rat', 'animal', 'mammifère'],
    '🐿️': ['écureuil', 'animal', 'mammifère'],
    '🦔': ['hérisson', 'animal', 'mammifère'],
    '🐾': ['empreintes d’animaux', 'animal', 'patte'],
    '🐉': ['dragon', 'animal', 'fantastique', 'monstre'],
    '🐲': ['tête de dragon', 'animal', 'fantastique', 'monstre'],
    '🌵': ['cactus', 'plante', 'désert'],
    '🎄': ['sapin de Noël', 'arbre', 'Noël', 'fête'],
    '🌲': ['conifère', 'arbre', 'plante'],
    '🌳': ['feuillu', 'arbre', 'plante'],
    '🌴': ['palmier', 'arbre', 'plante', 'tropical'],
    '🌱': ['jeune pousse', 'plante', 'croissance'],
    '🌿': ['herbe', 'plante', 'feuille'],
    '☘️': ['trèfle', 'plante', 'chance', 'Irlande'],
    '🍀': ['trèfle à quatre feuilles', 'plante', 'chance', 'porte-bonheur'],
    '🎍': ['pin décoratif', 'plante', 'Japon', 'Nouvel An'],
    '🎋': ['arbre à vœux', 'plante', 'Japon', 'tanabata'],
    '🍃': ['feuille flottant au vent', 'plante', 'vent', 'feuille'],
    '🍂': ['feuilles mortes', 'plante', 'automne', 'feuille'],
    '🍁': ['feuille d’érable', 'plante', 'Canada', 'automne'],
    '🍄': ['champignon', 'plante', 'nourriture'],
    '🌾': ['épi de riz', 'plante', 'céréale'],
    '💐': ['bouquet de fleurs', 'fleur', 'plante', 'cadeau'],
    '🌷': ['tulipe', 'fleur', 'plante'],
    '🌹': ['rose', 'fleur', 'plante', 'amour'],
    '🥀': ['rose fanée', 'fleur', 'plante', 'tristesse'],
    '🌺': ['hibiscus', 'fleur', 'plante', 'tropical'],
    '🌻': ['tournesol', 'fleur', 'plante', 'soleil'],
    '🌼': ['fleur', 'plante', 'marguerite'],
    '🌸': ['fleur de cerisier', 'fleur', 'plante', 'Japon', 'printemps'],
    '🌞': ['soleil avec visage', 'soleil', 'météo', 'jour'],
    '🌝': ['pleine lune avec visage', 'lune', 'nuit'],
    '🌚': ['nouvelle lune avec visage', 'lune', 'nuit'],
    '🌛': ['premier quartier de lune avec visage', 'lune', 'nuit'],
    '🌜': ['dernier quartier de lune avec visage', 'lune', 'nuit'],
    '🌡️': ['thermomètre', 'météo', 'température'],
    '☀️': ['soleil', 'météo', 'jour', 'beau temps'],
    '☁️': ['nuage', 'météo', 'couvert'],
    '⛅': ['soleil derrière un nuage', 'météo', 'partiellement nuageux'],
    '⛈️': ['nuage avec éclair et pluie', 'météo', 'orage'],
    '🌤️': ['soleil derrière un petit nuage', 'météo', 'éclaircie'],
    '🌥️': ['soleil derrière un grand nuage', 'météo', 'très nuageux'],
    '🌦️': ['soleil derrière un nuage de pluie', 'météo', 'averse'],
    '🌧️': ['nuage de pluie', 'météo', 'pluie'],
    '🌨️': ['nuage de neige', 'météo', 'neige'],
    '🌩️': ['nuage avec éclair', 'météo', 'orage'],
    '🌪️': ['tornade', 'météo', 'vent'],
    '🌫️': ['brouillard', 'météo'],
    '🌬️': ['vent', 'météo', 'visage'],
    '🌀': ['cyclone', 'météo', 'ouragan'],
    '🌈': ['arc-en-ciel', 'météo', 'pluie', 'soleil'],
    '🌂': ['parapluie fermé', 'météo', 'pluie'],
    '☂️': ['parapluie', 'météo', 'pluie'],
    '☔': ['parapluie avec des gouttes de pluie', 'météo', 'pluie'],
    '⛱️': ['parasol', 'plage', 'soleil'],
    '🔥': ['feu', 'flamme', 'chaud'],
    '💧': ['goutte d’eau', 'eau', 'pluie'],
    '🌊': ['vague', 'mer', 'océan'],
    '🍇': ['raisin', 'fruit', 'nourriture'],
    '🍈': ['melon', 'fruit', 'nourriture'],
    '🍉': ['pastèque', 'fruit', 'nourriture', 'été'],
    '🍊': ['mandarine', 'fruit', 'nourriture', 'orange'],
    '🍋': ['citron', 'fruit', 'nourriture', 'jaune'],
    '🍌': ['banane', 'fruit', 'nourriture'],
    '🍍': ['ananas', 'fruit', 'nourriture', 'tropical'],
    '🥭': ['mangue', 'fruit', 'nourriture', 'tropical'],
    '🍎': ['pomme rouge', 'fruit', 'nourriture'],
    '🍏': ['pomme verte', 'fruit', 'nourriture'],
    '🍐': ['poire', 'fruit', 'nourriture'],
    '🍑': ['pêche', 'fruit', 'nourriture'],
    '🍒': ['cerise', 'fruit', 'nourriture'],
    '🍓': ['fraise', 'fruit', 'nourriture'],
    '🥝': ['kiwi', 'fruit', 'nourriture'],
    '🍅': ['tomate', 'fruit', 'légume', 'nourriture'],
    '🥥': ['noix de coco', 'fruit', 'nourriture', 'tropical'],
    '🥑': ['avocat', 'fruit', 'nourriture'],
    '🍆': ['aubergine', 'légume', 'nourriture'],
    '🥔': ['pomme de terre', 'légume', 'nourriture'],
    '🥕': ['carotte', 'légume', 'nourriture'],
    '🌽': ['épi de maïs', 'légume', 'céréale', 'nourriture'],
    '🌶️': ['piment', 'légume', 'épice', 'nourriture'],
    '🥒': ['concombre', 'légume', 'nourriture'],
    '🥬': ['légume à feuilles', 'salade', 'nourriture'],
    '🥦': ['brocoli', 'légume', 'nourriture'],
    '🧄': ['ail', 'légume', 'épice', 'nourriture'],
    '🧅': ['oignon', 'légume', 'épice', 'nourriture'],
    '🥜': ['cacahuètes', 'nourriture', 'légumineuse'],
    '🌰': ['châtaigne', 'nourriture', 'automne'],
    '🍞': ['pain', 'nourriture', 'boulangerie'],
    '🥐': ['croissant', 'nourriture', 'viennoiserie', 'boulangerie'],
    '🥖': ['baguette', 'pain', 'nourriture', 'France'],
    '🥨': ['bretzel', 'nourriture', 'boulangerie'],
    '🥯': ['bagel', 'pain', 'nourriture'],
    '🥞': ['pancakes', 'crêpes', 'nourriture', 'petit-déjeuner'],
    '🧇': ['gaufre', 'nourriture', 'dessert'],
    '🧀': ['fromage', 'nourriture'],
    '🍖': ['viande sur os', 'nourriture'],
    '🍗': ['cuisse de poulet', 'nourriture', 'volaille'],
    '🥩': ['steak', 'viande', 'nourriture'],
    '🥓': ['bacon', 'viande', 'nourriture', 'porc'],
    '🍔': ['hamburger', 'nourriture', 'fast-food'],
    '🍟': ['frites', 'nourriture', 'fast-food'],
    '🍕': ['pizza', 'nourriture', 'italien'],
    '🌭': ['hot-dog', 'nourriture', 'fast-food'],
    '🥪': ['sandwich', 'nourriture'],
    '🌮': ['taco', 'nourriture', 'mexicain'],
    '🌯': ['burrito', 'nourriture', 'mexicain'],
    '🥙': ['kebab', 'nourriture', 'grec', 'turc'],
    '🧆': ['falafel', 'nourriture', 'végétarien'],
    '🥚': ['œuf', 'nourriture'],
    '🍳': ['œuf au plat', 'nourriture', 'cuisine'],
    '🥘': ['paella', 'nourriture', 'espagnol', 'plat'],
    '🍲': ['marmite', 'nourriture', 'soupe', 'ragoût'],
    '🥣': ['bol de céréales', 'nourriture', 'petit-déjeuner'],
    '🥗': ['salade verte', 'nourriture', 'sain'],
    '🍿': ['pop-corn', 'nourriture', 'cinéma'],
    '🧈': ['beurre', 'nourriture', 'produit laitier'],
    '🧂': ['sel', 'épice', 'nourriture'],
    '🥫': ['conserve', 'nourriture'],
    '🍱': ['bento', 'nourriture', 'japonais', 'boîte'],
    '🍘': ['cracker de riz', 'nourriture', 'japonais'],
    '🍙': ['boulette de riz', 'onigiri', 'nourriture', 'japonais'],
    '🍚': ['bol de riz', 'nourriture', 'asiatique'],
    '🍛': ['riz au curry', 'nourriture', 'indien', 'asiatique'],
    '🍜': ['bol de nouilles', 'ramen', 'nourriture', 'japonais'],
    '🍝': ['spaghetti', 'pâtes', 'nourriture', 'italien'],
    '🍠': ['patate douce', 'nourriture', 'légume'],
    '🍢': ['brochette japonaise', 'oden', 'nourriture'],
    '🍣': ['sushi', 'nourriture', 'japonais', 'poisson'],
    '🍤': ['crevette frite', 'tempura', 'nourriture', 'japonais'],
    '🍥': ['pâté de poisson', 'naruto', 'nourriture', 'japonais'],
    '🥮': ['gâteau de lune', 'nourriture', 'chinois', 'fête'],
    '🍡': ['dango', 'nourriture', 'japonais', 'dessert'],
    '🥟': ['ravioli', 'dumpling', 'nourriture', 'asiatique'],
    '🥠': ['biscuit chinois', 'fortune cookie', 'nourriture'],
    '🥡': ['boîte à emporter', 'nourriture', 'chinois'],
    '🍦': ['glace', 'dessert', 'nourriture'],
    '🍧': ['granité', 'dessert', 'nourriture'],
    '🍨': ['coupe de glace', 'dessert', 'nourriture'],
    '🍩': ['donut', 'dessert', 'nourriture', 'pâtisserie'],
    '🍪': ['cookie', 'biscuit', 'dessert', 'nourriture'],
    '🎂': ['gâteau d’anniversaire', 'dessert', 'nourriture', 'fête'],
    '🍰': ['part de gâteau', 'dessert', 'nourriture', 'pâtisserie'],
    '🧁': ['cupcake', 'dessert', 'nourriture', 'pâtisserie'],
    '🥧': ['tarte', 'dessert', 'nourriture', 'pâtisserie'],
    '🍫': ['tablette de chocolat', 'dessert', 'nourriture', 'sucrerie'],
    '🍬': ['bonbon', 'sucrerie', 'nourriture'],
    '🍭': ['sucette', 'bonbon', 'sucrerie', 'nourriture'],
    '🍮': ['flan', 'crème caramel', 'dessert', 'nourriture'],
    '🍯': ['pot de miel', 'nourriture', 'sucré'],
    '🍼': ['biberon', 'bébé', 'lait'],
    '🥛': ['verre de lait', 'boisson', 'produit laitier'],
    '☕': ['café', 'boisson chaude', 'tasse'],
    '🍵': ['thé', 'boisson chaude', 'tasse'],
    '🍶': ['saké', 'alcool', 'boisson', 'japonais'],
    '🍾': ['bouteille de champagne', 'alcool', 'boisson', 'fête'],
    '🍷': ['verre de vin', 'alcool', 'boisson'],
    '🍸': ['cocktail', 'alcool', 'boisson', 'verre'],
    '🍹': ['cocktail tropical', 'boisson', 'été'],
    '🍺': ['chope de bière', 'alcool', 'boisson'],
    '🍻': ['chopes de bière', 'alcool', 'boisson', 'trinquer'],
    '🥂': ['coupes de champagne', 'alcool', 'boisson', 'trinquer', 'fête'],
    '🥃': ['verre de whisky', 'alcool', 'boisson'],
    '🥤': ['gobelet avec paille', 'boisson', 'soda'],
    '🧃': ['brique de jus', 'boisson', 'jus'],
    '🧉': ['maté', 'boisson', 'infusion'],
    '🧊': ['glaçon', 'froid', 'eau'],
    '🥢': ['baguettes', 'ustensile', 'asiatique'],
    '🍽️': ['fourchette et couteau avec une assiette', 'ustensile', 'repas'],
    '🍴': ['fourchette et couteau', 'ustensile', 'cuisine'],
    '🥄': ['cuillère', 'ustensile', 'cuisine'],
    '🔪': ['couteau de cuisine', 'ustensile', 'arme'],
    '🏺': ['amphore', 'pot', 'vase', 'grec'],
    '🌍': ['globe terrestre Europe-Afrique', 'monde', 'terre', 'planète'],
    '🌎': ['globe terrestre Amériques', 'monde', 'terre', 'planète'],
    '🌏': ['globe terrestre Asie-Australie', 'monde', 'terre', 'planète'],
    '🌐': ['globe avec méridiens', 'monde', 'terre', 'internet'],
    '🗺️': ['carte du monde', 'carte', 'géographie', 'voyage'],
    '🗾': ['carte du Japon', 'Japon', 'carte'],
    '🧭': ['boussole', 'navigation', 'direction'],
    '🏔️': ['montagne enneigée', 'montagne', 'neige'],
    '⛰️': ['montagne', 'nature'],
    '🌋': ['volcan', 'montagne', 'éruption'],
    '🗻': ['mont Fuji', 'Japon', 'montagne'],
    '🏕️': ['camping', 'tente', 'nature'],
    '🏖️': ['plage avec parasol', 'plage', 'mer', 'vacances'],
    '🏜️': ['désert', 'sable', 'dune'],
    '🏝️': ['île déserte', 'île', 'palmier', 'tropical'],
    '🏞️': ['parc national', 'paysage', 'nature'],
    '🏟️': ['stade', 'sport', 'événement'],
    '🏛️': ['bâtiment classique', 'architecture', 'monument'],
    '🏗️': ['chantier de construction', 'construction', 'grue'],
    '🧱': ['brique', 'mur', 'construction'],
    '🏘️': ['maisons', 'ville', 'résidentiel'],
    '🏚️': ['maison abandonnée', 'ruine', 'vieux'],
    '🏠': ['maison', 'logement', 'domicile'],
    '🏡': ['maison avec jardin', 'logement', 'domicile'],
    '🏢': ['immeuble de bureaux', 'bâtiment', 'travail'],
    '🏣': ['bureau de poste japonais', 'poste', 'Japon'],
    '🏤': ['bureau de poste', 'poste', 'Europe'],
    '🏥': ['hôpital', 'médecine', 'santé'],
    '🏦': ['banque', 'argent', 'finance'],
    '🏨': ['hôtel', 'logement', 'voyage'],
    '🏩': ['love hotel', 'hôtel', 'amour', 'romance'],
    '🏪': ['supérette', 'magasin', 'commerce'],
    '🏫': ['école', 'éducation', 'bâtiment'],
    '🏬': ['grand magasin', 'magasin', 'commerce'],
    '🏭': ['usine', 'industrie', 'bâtiment'],
    '🏯': ['château japonais', 'Japon', 'château'],
    '🏰': ['château', 'Europe', 'fort'],
    '💒': ['mariage', 'chapelle', 'église'],
    '🗼': ['tour de Tokyo', 'Japon', 'Tokyo', 'tour'],
    '🗽': ['statue de la Liberté', 'États-Unis', 'New York', 'statue'],
    '⛪': ['église', 'religion', 'christianisme'],
    '🕌': ['mosquée', 'religion', 'islam'],
    '🛕': ['temple hindou', 'religion', 'hindouisme'],
    '🕍': ['synagogue', 'religion', 'judaïsme'],
    '⛩️': ['sanctuaire shinto', 'religion', 'Japon'],
    '🕋': ['Kaaba', 'religion', 'islam', 'Mecque'],
    '⛲': ['fontaine', 'eau', 'parc'],
    '⛺': ['tente', 'camping', 'nature'],
    '🌁': ['brouillard', 'météo', 'ville'],
    '🌃': ['nuit étoilée', 'nuit', 'ville'],
    '🏙️': ['paysage urbain', 'ville', 'bâtiment'],
    '🌄': ['lever de soleil sur les montagnes', 'soleil', 'montagne', 'matin'],
    '🌅': ['lever de soleil', 'soleil', 'mer', 'matin'],
    '🌆': ['crépuscule', 'ville', 'soir'],
    '🌇': ['coucher de soleil', 'soleil', 'ville', 'soir'],
    '🌉': ['pont de nuit', 'pont', 'nuit', 'ville'],
    '♨️': ['sources chaudes', 'bain', 'Japon'],
    '🎠': ['manège', 'parc d’attractions', 'cheval'],
    '🎡': ['grande roue', 'parc d’attractions', 'roue'],
    '🎢': ['montagnes russes', 'parc d’attractions', 'sensations'],
    '💈': ['enseigne de barbier', 'barbier', 'coiffeur'],
    '🎪': ['chapiteau de cirque', 'cirque', 'tente'],
    '🚂': ['locomotive à vapeur', 'train', 'transport'],
    '🚃': ['wagon', 'train', 'transport'],
    '🚄': ['train à grande vitesse', 'train', 'transport'],
    '🚅': ['Shinkansen', 'train', 'Japon', 'transport'],
    '🚆': ['train', 'transport', 'ferroviaire'],
    '🚇': ['métro', 'transport', 'ville'],
    '🚈': ['train léger', 'transport', 'ville'],
    '🚉': ['gare', 'train', 'transport'],
    '🚊': ['tramway', 'transport', 'ville'],
    '🚝': ['monorail', 'transport', 'ville'],
    '🚞': ['train de montagne', 'transport', 'montagne'],
    '🚋': ['wagon de tramway', 'transport', 'ville'],
    '🚌': ['bus', 'transport', 'ville'],
    '🚍': ['bus arrivant', 'transport', 'ville'],
    '🚎': ['trolleybus', 'transport', 'ville'],
    '🚐': ['minibus', 'transport', 'van'],
    '🚑': ['ambulance', 'urgence', 'secours'],
    '🚒': ['camion de pompiers', 'pompier', 'feu'],
    '🚓': ['voiture de police', 'police', 'urgence'],
    '🚔': ['voiture de police arrivant', 'police', 'urgence'],
    '🚕': ['taxi', 'transport', 'voiture'],
    '🚖': ['taxi arrivant', 'transport', 'voiture'],
    '🚗': ['voiture', 'transport', 'automobile'],
    '🚘': ['voiture arrivant', 'transport', 'automobile'],
    '🚙': ['SUV', 'voiture', 'transport'],
    '🚚': ['camion de livraison', 'transport', 'camion'],
    '🚛': ['poids lourd', 'transport', 'camion'],
    '🚜': ['tracteur', 'agriculture', 'véhicule'],
    '🏎️': ['voiture de course', 'sport', 'vitesse'],
    '🏍️': ['moto', 'transport', 'deux-roues'],
    '🛵': ['scooter', 'transport', 'deux-roues'],
    '🚲': ['vélo', 'bicyclette', 'transport', 'sport'],
    '🛴': ['trottinette', 'transport'],
    '🛹': ['skateboard', 'sport', 'planche'],
    '🚏': ['arrêt de bus', 'transport', 'bus'],
    '🛣️': ['autoroute', 'route', 'transport'],
    '🛤️': ['voie ferrée', 'train', 'transport'],
    '🛢️': ['baril de pétrole', 'industrie', 'énergie'],
    '⛽': ['pompe à essence', 'carburant', 'voiture'],
    '🚨': ['gyrophare', 'police', 'urgence'],
    '🚥': ['feux de circulation horizontaux', 'route', 'circulation'],
    '🚦': ['feux de circulation verticaux', 'route', 'circulation'],
    '🛑': ['panneau stop', 'route', 'circulation'],
    '🚧': ['chantier', 'route', 'construction'],
    '⚓': ['ancre', 'bateau', 'mer'],
    '⛵': ['voilier', 'bateau', 'mer', 'sport'],
    '🛶': ['canoë', 'bateau', 'sport'],
    '🚤': ['bateau à moteur', 'bateau', 'mer'],
    '🛳️': ['navire à passagers', 'bateau', 'croisière'],
    '⛴️': ['ferry', 'bateau', 'transport'],
    '🚢': ['navire', 'bateau', 'transport', 'mer'],
    '✈️': ['avion', 'transport', 'aérien', 'voyage'],
    '🛩️': ['petit avion', 'transport', 'aérien'],
    '🛫': ['décollage d’avion', 'transport', 'aéroport'],
    '🛬': ['atterrissage d’avion', 'transport', 'aéroport'],
    '💺': ['siège', 'transport', 'avion', 'train'],
    '🚁': ['hélicoptère', 'transport', 'aérien'],
    '🚟': ['téléphérique', 'transport', 'montagne'],
    '🚠': ['télécabine', 'transport', 'montagne'],
    '🚡': ['téléphérique', 'transport', 'montagne'],
    '🛰️': ['satellite', 'espace', 'communication'],
    '🚀': ['fusée', 'espace', 'lancement'],
    '🛸': ['ovni', 'extraterrestre', 'espace'],
    '🛎️': ['sonnette de réception', 'hôtel', 'service'],
    '🧳': ['valise', 'voyage', 'bagage'],
    '⌛': ['sablier', 'temps', 'attente'],
    '⏳': ['sablier qui s’écoule', 'temps', 'attente'],
    '⌚': ['montre', 'temps', 'accessoire'],
    '⏰': ['réveil', 'temps', 'matin'],
    '⏱️': ['chronomètre', 'temps', 'sport'],
    '⏲️': ['minuteur', 'temps', 'cuisine'],
    '🕰️': ['horloge de cheminée', 'temps', 'horloge'],
    '🎈': ['ballon', 'fête', 'anniversaire'],
    '🎉': ['cotillons', 'fête', 'célébration'],
    '🎊': ['boule de confettis', 'fête', 'célébration'],
    '🎎': ['poupées japonaises', 'Japon', 'fête'],
    '🎏': ['banderoles de carpes', 'Japon', 'fête'],
    '🎐': ['carillon à vent', 'Japon', 'été'],
    '🧧': ['enveloppe rouge', 'cadeau', 'argent', 'Chine'],
    '🎀': ['ruban', 'cadeau', 'décoration'],
    '🎁': ['cadeau', 'fête', 'anniversaire'],
    '🎗️': ['ruban de commémoration', 'souvenir', 'cause'],
    '🎟️': ['ticket', 'événement', 'entrée'],
    '🎫': ['billet', 'événement', 'transport'],
    '🎖️': ['médaille militaire', 'militaire', 'récompense'],
    '🏆': ['trophée', 'récompense', 'victoire', 'sport'],
    '🏅': ['médaille sportive', 'récompense', 'sport'],
    '🥇': ['médaille d’or', 'récompense', 'premier'],
    '🥈': ['médaille d’argent', 'récompense', 'deuxième'],
    '🥉': ['médaille de bronze', 'récompense', 'troisième'],
    '⚽': ['ballon de football', 'sport', 'football'],
    '⚾': ['balle de baseball', 'sport', 'baseball'],
    '🥎': ['balle de softball', 'sport', 'softball'],
    '🏀': ['ballon de basket-ball', 'sport', 'basket-ball'],
    '🏐': ['ballon de volley-ball', 'sport', 'volley-ball'],
    '🏈': ['ballon de football américain', 'sport', 'football américain'],
    '🏉': ['ballon de rugby', 'sport', 'rugby'],
    '🎾': ['balle de tennis', 'sport', 'tennis'],
    '🥏': ['frisbee', 'sport', 'jeu'],
    '🎳': ['bowling', 'sport', 'jeu'],
    '🏏': ['cricket', 'sport', 'jeu'],
    '🏑': ['hockey sur gazon', 'sport', 'jeu'],
    '🏒': ['hockey sur glace', 'sport', 'jeu'],
    '🥍': ['crosse', 'sport', 'jeu'],
    '🏓': ['tennis de table', 'ping-pong', 'sport'],
    '🏸': ['badminton', 'sport', 'jeu'],
    '🥊': ['gant de boxe', 'sport', 'boxe'],
    '🥋': ['kimono', 'sport', 'arts martiaux'],
    '🥅': ['but', 'sport', 'football', 'hockey'],
    '⛳': ['trou de golf', 'sport', 'golf'],
    '⛸️': ['patin à glace', 'sport', 'hiver'],
    '🎣': ['canne à pêche', 'sport', 'pêche'],
    '🎽': ['maillot de sport', 'sport', 'course'],
    '🎿': ['skis', 'sport', 'hiver'],
    '🛷': ['luge', 'sport', 'hiver'],
    '🥌': ['curling', 'sport', 'hiver'],
    '🎯': ['cible', 'jeu', 'fléchettes'],
    '🎱': ['boule de billard numéro 8', 'jeu', 'billard'],
    '🔮': ['boule de cristal', 'divination', 'magie'],
    '🧿': ['nazar', 'amulette', 'protection'],
    '🎮': ['manette de jeu vidéo', 'jeu', 'vidéo'],
    '🕹️': ['joystick', 'jeu', 'vidéo'],
    '🎰': ['machine à sous', 'jeu', 'casino'],
    '🎲': ['dé', 'jeu', 'hasard'],
    '🧩': ['puzzle', 'jeu', 'pièce'],
    '🧸': ['ours en peluche', 'jouet', 'enfant'],
    '♠️': ['pique', 'carte', 'jeu'],
    '♥️': ['cœur', 'carte', 'jeu'],
    '♦️': ['carreau', 'carte', 'jeu'],
    '♣️': ['trèfle', 'carte', 'jeu'],
    '♟️': ['pion', 'échecs', 'jeu'],
    '🃏': ['joker', 'carte', 'jeu'],
    '🀄': ['dragon rouge', 'mahjong', 'jeu'],
    '🎴': ['cartes à jouer des fleurs', 'jeu', 'Japon'],
    '🎭': ['masques de théâtre', 'théâtre', 'art'],
    '🖼️': ['cadre', 'art', 'peinture'],
    '🎨': ['palette de peinture', 'art', 'peinture'],
    '🧵': ['fil', 'couture', 'artisanat'],
    '🧶': ['pelote de laine', 'tricot', 'artisanat'],
    '👓': ['lunettes', 'vue', 'accessoire'],
    '🕶️': ['lunettes de soleil', 'accessoire', 'soleil'],
    '🥽': ['lunettes de protection', 'protection', 'science'],
    '🥼': ['blouse de laboratoire', 'science', 'docteur'],
    '🦺': ['gilet de sécurité', 'sécurité', 'construction'],
    '👔': ['cravate', 'vêtement', 'formel'],
    '👕': ['t-shirt', 'vêtement'],
    '👖': ['jean', 'vêtement', 'pantalon'],
    '🧣': ['écharpe', 'vêtement', 'hiver'],
    '🧤': ['gants', 'vêtement', 'hiver'],
    '🧥': ['manteau', 'vêtement', 'hiver'],
    '🧦': ['chaussettes', 'vêtement'],
    '👗': ['robe', 'vêtement', 'femme'],
    '👘': ['kimono', 'vêtement', 'Japon'],
    '🥻': ['sari', 'vêtement', 'Inde'],
    '🩱': ['maillot de bain une pièce', 'vêtement', 'natation'],
    '🩲': ['slip', 'sous-vêtement', 'homme'],
    '🩳': ['short', 'vêtement', 'été'],
    '👙': ['bikini', 'maillot de bain', 'vêtement'],
    '👚': ['blouse', 'vêtement', 'femme'],
    '👛': ['porte-monnaie', 'argent', 'accessoire'],
    '👜': ['sac à main', 'accessoire', 'femme'],
    '👝': ['pochette', 'sac', 'accessoire'],
    '🎒': ['sac à dos', 'école', 'voyage'],
    '👞': ['chaussure homme', 'vêtement', 'chaussure'],
    '👟': ['basket', 'chaussure', 'sport'],
    '🥾': ['chaussure de randonnée', 'chaussure', 'montagne'],
    '🥿': ['ballerine', 'chaussure', 'femme'],
    '👠': ['chaussure à talon haut', 'chaussure', 'femme'],
    '👡': ['sandale', 'chaussure', 'été'],
    '🩰': ['chausson de danse', 'danse', 'ballet'],
    '👢': ['botte', 'chaussure', 'hiver'],
    '👑': ['couronne', 'royal', 'roi', 'reine'],
    '👒': ['chapeau de femme', 'accessoire', 'été'],
    '🎩': ['haut-de-forme', 'chapeau', 'magie', 'formel'],
    '🎓': ['toque de diplômé', 'diplôme', 'université'],
    '🧢': ['casquette', 'chapeau', 'accessoire'],
    '⛑️': ['casque de secours', 'secours', 'protection'],
    '📿': ['chapelet', 'religion', 'prière'],
    '💄': ['rouge à lèvres', 'maquillage', 'beauté'],
    '💍': ['bague', 'bijou', 'mariage'],
    '💎': ['diamant', 'bijou', 'précieux'],
    '🔇': ['haut-parleur barré', 'son', 'silence'],
    '🔈': ['haut-parleur', 'son', 'volume'],
    '🔉': ['haut-parleur avec une onde sonore', 'son', 'volume'],
    '🔊': ['haut-parleur avec trois ondes sonores', 'son', 'volume'],
    '📢': ['mégaphone', 'son', 'annonce'],
    '📣': ['porte-voix', 'son', 'annonce'],
    '📯': ['cor de postillon', 'musique', 'instrument'],
    '🔔': ['cloche', 'son', 'notification'],
    '🔕': ['cloche barrée', 'son', 'silence'],
    '🎼': ['partition', 'musique', 'note'],
    '🎵': ['note de musique', 'son', 'musique'],
    '🎶': ['notes de musique', 'son', 'musique'],
    '🎙️': ['micro de studio', 'musique', 'radio'],
    '🎚️': ['curseur de réglage', 'musique', 'son'],
    '🎛️': ['bouton de réglage', 'musique', 'son'],
    '🎤': ['microphone', 'musique', 'chanter'],
    '🎧': ['casque audio', 'musique', 'son'],
    '📻': ['radio', 'musique', 'son'],
    '🎷': ['saxophone', 'musique', 'instrument'],
    '🎸': ['guitare', 'musique', 'instrument'],
    '🎹': ['clavier de piano', 'musique', 'instrument'],
    '🎺': ['trompette', 'musique', 'instrument'],
    '🎻': ['violon', 'musique', 'instrument'],
    '🪕': ['banjo', 'musique', 'instrument'],
    '🥁': ['tambour', 'musique', 'instrument'],
    '📱': ['téléphone portable', 'technologie', 'communication'],
    '📲': ['téléphone portable avec une flèche', 'appel', 'communication'],
    '☎️': ['téléphone', 'fixe', 'communication'],
    '📞': ['combiné téléphonique', 'appel', 'communication'],
    '📟': ['bipeur', 'communication', 'technologie'],
    '📠': ['fax', 'communication', 'technologie'],
    '🔋': ['batterie', 'énergie', 'technologie'],
    '🔌': ['prise électrique', 'électricité', 'énergie'],
    '💻': ['ordinateur portable', 'technologie', 'informatique'],
    '🖥️': ['ordinateur de bureau', 'technologie', 'informatique'],
    '🖨️': ['imprimante', 'technologie', 'bureau'],
    '⌨️': ['clavier', 'ordinateur', 'technologie'],
    '🖱️': ['souris d’ordinateur', 'technologie', 'informatique'],
    '🖲️': ['trackball', 'ordinateur', 'technologie'],
    '💽': ['disque d’ordinateur', 'technologie', 'stockage'],
    '💾': ['disquette', 'technologie', 'stockage', 'ancien'],
    '💿': ['disque optique', 'CD', 'DVD', 'technologie'],
    '📀': ['DVD', 'film', 'technologie'],
    '🧮': ['boulier', 'calcul', 'mathématiques'],
    '🎥': ['caméra', 'cinéma', 'film'],
    '🎞️': ['pellicule', 'cinéma', 'film'],
    '📽️': ['projecteur de film', 'cinéma', 'film'],
    '🎬': ['clap de cinéma', 'cinéma', 'film'],
    '📺': ['télévision', 'technologie', 'média'],
    '📷': ['appareil photo', 'photographie', 'technologie'],
    '📸': ['appareil photo avec flash', 'photographie', 'technologie'],
    '📹': ['caméscope', 'vidéo', 'technologie'],
    '📼': ['cassette vidéo', 'film', 'technologie', 'ancien'],
    '🔍': ['loupe orientée à gauche', 'recherche', 'zoom'],
    '🔎': ['loupe orientée à droite', 'recherche', 'zoom'],
    '🕯️': ['bougie', 'lumière', 'feu'],
    '💡': ['ampoule', 'idée', 'lumière'],
    '🔦': ['lampe de poche', 'lumière', 'outil'],
    '🏮': ['lanterne rouge', 'lumière', 'Japon'],
    '🪔': ['diya', 'lampe', 'Inde', 'hindouisme'],
    '📔': ['carnet à spirales', 'bureau', 'note'],
    '📕': ['livre fermé', 'lecture', 'éducation'],
    '📖': ['livre ouvert', 'lecture', 'éducation'],
    '📗': ['livre vert', 'lecture', 'éducation'],
    '📘': ['livre bleu', 'lecture', 'éducation'],
    '📙': ['livre orange', 'lecture', 'éducation'],
    '📚': ['livres', 'lecture', 'bibliothèque'],
    '📓': ['carnet', 'bureau', 'note'],
    '📒': ['grand livre', 'bureau', 'note'],
    '📃': ['page avec le coin replié', 'document', 'bureau'],
    '📜': ['parchemin', 'document', 'histoire'],
    '📄': ['page', 'document', 'bureau'],
    '📰': ['journal', 'presse', 'information'],
    '🗞️': ['journal enroulé', 'presse', 'information'],
    '📑': ['onglets de signets', 'bureau', 'organisation'],
    '🔖': ['signet', 'lecture', 'bureau'],
    '🏷️': ['étiquette', 'prix', 'magasin'],
    '💰': ['sac d’argent', 'argent', 'finance'],
    '💴': ['billet de yen', 'argent', 'Japon'],
    '💵': ['billet de dollar', 'argent', 'États-Unis'],
    '💶': ['billet d’euro', 'argent', 'Europe'],
    '💷': ['billet de livre sterling', 'argent', 'Royaume-Uni'],
    '💸': ['argent avec des ailes', 'perte', 'dépense'],
    '💳': ['carte de crédit', 'argent', 'paiement'],
    '🧾': ['reçu', 'facture', 'paiement'],
    '💹': ['graphique de marché en hausse', 'finance', 'bourse'],
    '✉️': ['enveloppe', 'courrier', 'email'],
    '📧': ['e-mail', 'courrier', 'internet'],
    '📨': ['courrier entrant', 'enveloppe', 'email'],
    '📩': ['courrier sortant', 'enveloppe', 'email'],
    '📤': ['boîte d’envoi', 'courrier', 'bureau'],
    '📥': ['boîte de réception', 'courrier', 'bureau'],
    '📦': ['colis', 'boîte', 'livraison'],
    '📫': ['boîte aux lettres fermée avec drapeau levé', 'courrier', 'poste'],
    '📪': ['boîte aux lettres fermée avec drapeau baissé', 'courrier', 'poste'],
    '📬': ['boîte aux lettres ouverte avec drapeau levé', 'courrier', 'poste'],
    '📭': [
        'boîte aux lettres ouverte avec drapeau baissé',
        'courrier',
        'poste',
    ],
    '📮': ['boîte aux lettres', 'courrier', 'poste'],
    '🗳️': ['urne', 'élection', 'vote'],
    '✏️': ['crayon', 'écriture', 'bureau'],
    '✒️': ['plume', 'écriture', 'bureau'],
    '🖋️': ['stylo-plume', 'écriture', 'bureau'],
    '🖊️': ['stylo', 'écriture', 'bureau'],
    '🖌️': ['pinceau', 'art', 'peinture'],
    '🖍️': ['crayon de cire', 'dessin', 'art'],
    '📝': ['mémo', 'écriture', 'bureau'],
    '💼': ['mallette', 'travail', 'bureau'],
    '📁': ['dossier', 'bureau', 'organisation'],
    '📂': ['dossier ouvert', 'bureau', 'organisation'],
    '🗂️': ['intercalaires', 'bureau', 'organisation'],
    '📅': ['calendrier', 'date', 'temps'],
    '📆': ['calendrier détachable', 'date', 'temps'],
    '🗒️': ['bloc-notes à spirales', 'bureau', 'note'],
    '🗓️': ['calendrier à spirales', 'date', 'temps'],
    '📇': ['fiches', 'bureau', 'organisation'],
    '📈': ['graphique en hausse', 'finance', 'tendance'],
    '📉': ['graphique en baisse', 'finance', 'tendance'],
    '📊': ['graphique à barres', 'statistiques', 'finance'],
    '📋': ['presse-papiers', 'bureau', 'note'],
    '📌': ['punaise', 'bureau', 'épingler'],
    '📍': ['épingle', 'carte', 'localisation'],
    '📎': ['trombone', 'bureau', 'attacher'],
    '🖇️': ['trombones', 'bureau', 'attacher'],
    '📏': ['règle', 'mesure', 'bureau'],
    '📐': ['équerre', 'mesure', 'bureau'],
    '✂️': ['ciseaux', 'couper', 'bureau'],
    '🗃️': ['classeur', 'bureau', 'organisation'],
    '🗄️': ['meuble de classement', 'bureau', 'organisation'],
    '🗑️': ['corbeille', 'poubelle', 'bureau'],
    '🔒': ['cadenas fermé', 'sécurité', 'fermé'],
    '🔓': ['cadenas ouvert', 'sécurité', 'ouvert'],
    '🔏': ['cadenas fermé avec un stylo', 'sécurité', 'privé'],
    '🔐': ['cadenas fermé avec une clé', 'sécurité', 'privé'],
    '🔑': ['clé', 'sécurité', 'ouvrir'],
    '🗝️': ['vieille clé', 'sécurité', 'indice'],
    '🔨': ['marteau', 'outil', 'construction'],
    '🪓': ['hache', 'outil', 'bois'],
    '⛏️': ['pioche', 'outil', 'mine'],
    '⚒️': ['marteau et pioche', 'outil', 'travail'],
    '🛠️': ['marteau et clé', 'outil', 'réparation'],
    '🗡️': ['dague', 'arme', 'couteau'],
    '⚔️': ['épées croisées', 'arme', 'combat'],
    '🔫': ['pistolet', 'arme', 'violence'],
    '🏹': ['arc et flèche', 'arme', 'sport'],
    '🛡️': ['bouclier', 'arme', 'protection'],
    '🔧': ['clé à molette', 'outil', 'réparation'],
    '🔩': ['écrou et boulon', 'outil', 'construction'],
    '⚙️': ['engrenage', 'outil', 'mécanique'],
    '🗜️': ['étau', 'outil', 'serrer'],
    '⚗️': ['alambic', 'science', 'chimie'],
    '🧪': ['tube à essai', 'science', 'chimie'],
    '🧫': ['boîte de Petri', 'science', 'biologie'],
    '🧬': ['ADN', 'science', 'biologie'],
    '🔬': ['microscope', 'science', 'recherche'],
    '🔭': ['télescope', 'science', 'astronomie'],
    '📡': ['antenne satellite', 'communication', 'technologie'],
    '💉': ['seringue', 'médecine', 'vaccin'],
    '🩸': ['goutte de sang', 'médecine', 'don'],
    '💊': ['pilule', 'médecine', 'médicament'],
    '🩹': ['pansement', 'médecine', 'blessure'],
    '🩺': ['stéthoscope', 'médecine', 'docteur'],
    '🚪': ['porte', 'maison', 'entrée'],
    '🛏️': ['lit', 'dormir', 'meuble'],
    '🛋️': ['canapé et lampe', 'meuble', 'salon'],
    '🪑': ['chaise', 'meuble', 's’asseoir'],
    '🚽': ['toilettes', 'salle de bain'],
    '🚿': ['douche', 'salle de bain', 'laver'],
    '🛁': ['baignoire', 'salle de bain', 'bain'],
    '🪒': ['rasoir', 'salle de bain', 'se raser'],
    '🧴': ['bouteille de lotion', 'soin', 'crème'],
    '🧷': ['épingle de sûreté', 'couture', 'attacher'],
    '🧹': ['balai', 'nettoyage', 'ménage'],
    '🧺': ['panier', 'linge', 'nettoyage'],
    '🧻': ['rouleau de papier', 'toilettes', 'papier toilette'],
    '🧼': ['savon', 'nettoyage', 'laver'],
    '🧽': ['éponge', 'nettoyage', 'laver'],
    '🧯': ['extincteur', 'feu', 'sécurité'],
    '🛒': ['caddie', 'courses', 'magasin'],
    '🚬': ['cigarette', 'fumer', 'tabac'],
    '⚰️': ['cercueil', 'mort', 'funérailles'],
    '⚱️': ['urne funéraire', 'mort', 'funérailles'],
    '🗿': ['moaï', 'statue', 'île de Pâques'],
};
