name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: yarn install

      - name: 👷 Build project
        run: yarn build

      - name: 🧑‍🔬 Run unit tests
        run: yarn test
